version: '3'

services:
  python_app:
    build:
        context: .
        dockerfile: Dockerfile.dev
    volumes:
        - ./:/app
    container_name: python_app
    ports:
      - "8501:8501"
    working_dir: /app
    environment:
      - BASE_DIR=/app
      - PYTHONPATH=/app
      - ENV=local
    tty: true
    stdin_open: true