FROM python:3.10

COPY ./ ./app/
WORKDIR /app
RUN pip install poetry==1.5.1

RUN poetry install

EXPOSE 8501

HEALTHCHECK CMD curl --fail http://localhost:8501/_stcore/health

ENTRYPOINT ["poetry", "run", "streamlit", "run", "src/main.py", "--server.port=8501", "--server.address=0.0.0.0"]